services:
  mtcore:
    build:
      context: .
      dockerfile: Dockerfile
      target: mtcore
    image: moontrader-mtcore
    container_name: moontrader-mtcore
    init: true
    restart: always
    stdin_open: true
    tty: true
    stop_signal: SIGTERM
    stop_grace_period: 30s
    ports:
      - "4242:4242/udp"
    volumes:
      - ./moontrader-data:/root/.config/moontrader-data