string = "1000FLOKI,1000LUNC,1000PEPE,1000SHIB,1000XEC,1INCH,AAVE,ACH,ADA,AGIX,ALGO,ALICE,ALPHA,AMB,ANKR,ANT,APE,API3,APT,AR,ARB,ARPA,ASTR,ATA,ATOM,AUDIO,AVAX,AXS,BAKE,BAL,BAND,BAT,BCH,BEL,BLUEBIRD,BLUR,BLZ,BNB,BNX,BTC,BTCDOM,BTCST,BTC_0630,BTS,C98,CELO,CELR,CFX,CHR,CHZ,CKB,COCOS,COMP,COTI,CRV,CTK,CTSI,CVC,CVX,DAR,DASH,DEFI,DENT,DGB,DOGE,DOT,DUSK,DYDX,EDU,EGLD,ENJ,ENS,EOS,ETC,ETH,ETH_0630,FET,FIL,FLM,FLOW,FOOTBALL,FTM,FTT,FXS,GAL,GALA,GMT,GMX,GRT,GTC,HBAR,HFT,HIGH,HNT,HOOK,HOT,ICP,ICX,ID,IDEX,IMX,INJ,IOST,IOTA,IOTX,JASMY,JOE,KAVA,KLAY,KNC,KSM,LDO,LEVER,LINA,LINK,LIT,LPT,LQTY,LRC,LTC,LUNA2,MAGIC,MANA,MASK,MATIC,MINA,MKR,MTL,NEAR,NEO,NKN,OCEAN,OGN,OMG,ONE,ONT,OP,PEOPLE,PERP,PHB,QNT,QTUM,RAD,RAY,RDNT,REEF,REN,RLC,RNDR,ROSE,RSR,RUNE,RVN,SAND,SC,SFP,SKL,SNX,SOL,SPELL,SRM,SSV,STG,STMX,STORJ,STX,SUI,SUSHI,SXP,T,THETA,TLM,TOMO,TRB,TRU,TRX,UMA,UNFI,UNI,USDC,VET,WAVES,WOO,XEM,XLM,XMR,XRP,XTZ,XVS,YFI,ZEC,ZEN,ZIL,ZRX"

elements = string.split(",")
result = [",".join(elements[i:i+9]) for i in range(0, len(elements), 9)]

for line in result:
    print(line)
